# https://www.jeffgeerling.com/blog/simple-glusterfs-setup-ansible

- hosts: gluster
  become: yes

  tasks:

  - name: format volume
    filesystem:
      fstype: xfs
      dev: /dev/vdb

  - name: mount volume
    mount:
      fstype: xfs
      path: /srv/gluster
      src: /dev/vdb
      state: mounted

  - name: gluster yum repo
    yum:
      name: centos-release-gluster312
      state: present

  - name: install gluster
    yum:
      name:
      - glusterfs-server
      - glusterfs-client
      state: present

  - name: start and enable gluster
    service:
      name: glusterd
      enabled: yes
      state: started

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

  - name: configure gluster volume
    gluster_volume:
      state: present
      name: "{{ gluster_brick_name }}"
      brick: "{{ gluster_brick_dir }}"
      replicas: "{{ (groups.gluster | length) > 1 | ternary(groups.gluster | length, omit) }}"
      cluster: "{{ groups.gluster | join(',') }}"
      host: "{{ inventory_hostname }}"
    run_once: true

  - name: mount gluster volume
    mount:
      name: "{{ gluster_mount_dir }}"
      src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted

  vars:
    gluster_brick_name: bricktest
    gluster_brick_dir: /srv/gluster/brick
    gluster_mount_dir: /mnt/gluster
